--[[
    Warcraft Online — localization: english.
]]

WO.Lang.Register("en", {
    -----------------------------------------------------------------------
    -- Common
    -----------------------------------------------------------------------
    ["ui.ok"] = "OK",
    ["ui.cancel"] = "Cancel",
    ["ui.close"] = "Close",
    ["ui.back"] = "Back",
    ["ui.next"] = "Next",
    ["ui.confirm"] = "Confirm",
    ["ui.delete"] = "Delete",
    ["ui.create"] = "Create",
    ["ui.save"] = "Save",
    ["ui.yes"] = "Yes",
    ["ui.no"] = "No",

    -----------------------------------------------------------------------
    -- Character
    -----------------------------------------------------------------------
    ["character.create"] = "Character Creation",
    ["character.select"] = "Character Selection",
    ["character.create_failed"] = "Failed to create character",
    ["character.select_failed"] = "Failed to select character",
    ["character.deleted"] = "Character deleted",
    ["character.delete_failed"] = "Failed to delete character",
    ["character.delete_confirm"] = "Are you sure you want to delete this character?",
    ["character.no_characters"] = "You have no characters",
    ["character.logout"] = "Leave character",
    ["character.main_menu"] = "Character Menu",
    ["character.menu.create"] = "Create Character",
    ["character.menu.load"] = "Load Character",
    ["character.menu.exit"] = "Exit",
    ["character.no_saved_characters"] = "No saved characters yet",
    ["character.back_to_menu"] = "Back to Menu",
    ["character.rotate_left"] = "Rotate Left",
    ["character.rotate_right"] = "Rotate Right",
    ["character.rotate_hint"] = "Drag the model or use the rotation buttons",
    ["character.model_preview_unavailable"] = "3D preview temporarily unavailable; waiting for the model to mount.",
    ["character.no_models_available"] = "No race models were detected in this session. Refresh the menu; if this repeats, check Workshop mounting on the client and server.",
    ["character.model_unavailable"] = "The model was not detected in this session's mounted content. Refresh the menu and try again.",

    ["character.step.race"] = "Race",
    ["character.step.gender"] = "Gender",
    ["character.step.age"] = "Age",
    ["character.step.name"] = "Name",
    ["character.step.surname"] = "Surname",
    ["character.step.customization"] = "Appearance",
    ["character.step.class"] = "Class",
    ["character.step.preview"] = "Preview",
    ["character.step.confirm"] = "Confirmation",

    ["character.name"] = "Name",
    ["character.surname"] = "Surname",
    ["character.age"] = "Age",
    ["character.gender"] = "Gender",
    ["character.race"] = "Race",
    ["character.class"] = "Class",
    ["character.model"] = "Model",
    ["character.level"] = "Level",
    ["character.full_name"] = "Full name",
    ["character.selected_class"] = "Selected class",
    ["character.class_unselected"] = "not selected",
    ["character.review_instructions"] = "Review the character details and tick the confirmation below to submit.",
    ["character.create_confirm_check"] = "I confirm that I want to create this character",
    ["character.create_confirm_action"] = "Confirm and create",
    ["character.confirm_required"] = "Confirm character creation before submitting",

    ["menu.title"] = "Warcraft Online",
    ["menu.fullscreen_subtitle"] = "Your adventure begins with your hero",
    ["menu.character_preview"] = "Your Character",
    ["menu.character_start_hint"] = "Create a hero, choose a race and class, then enter the world.",
    ["menu.overview"] = "Overview and Players",
    ["menu.overview_subtitle"] = "Character status and players currently on the server",
    ["menu.characters"] = "Characters",
    ["menu.characters_subtitle"] = "Create a character or load a saved one",
    ["menu.inventory"] = "Inventory",
    ["menu.sheet"] = "Character Stats",
    ["menu.quests"] = "Quest Journal",
    ["menu.settings"] = "Settings",
    ["settings.title"] = "Game Settings",
    ["settings.auto_collect"] = "Auto-collect valuable resources",
    ["settings.auto_collect_on"] = "Auto-collect: ON",
    ["settings.auto_collect_off"] = "Auto-collect: OFF",
    ["settings.auto_collect_hint"] = "When enabled, the server automatically collects nearby quest, rare, and valuable items, plus coins. Ordinary items are ignored unless an active quest needs them.",
    ["settings.auto_collect_status"] = "Syncing this setting with the server…",
    ["weapon.selector_title"] = "WEAPONS · 1–6 / wheel",
    ["menu.players"] = "Players on Server",
    ["menu.server_players"] = "Players",
    ["menu.no_players"] = "The player list is empty",
    ["menu.no_character"] = "No character is selected. Create a new one or load a saved character.",
    ["menu.character_none"] = "No active character",
    ["menu.saved_characters"] = "Saved characters",
    ["menu.logout_before_switch"] = "Leave the active character before switching.",
    ["menu.exit"] = "Disconnect",

    ["gender.male"] = "Male",
    ["gender.female"] = "Female",

    -----------------------------------------------------------------------
    -- Stats
    -----------------------------------------------------------------------
    ["stats.strength"] = "Strength",
    ["stats.agility"] = "Agility",
    ["stats.intelligence"] = "Intelligence",
    ["stats.stamina"] = "Stamina",
    ["stats.spirit"] = "Spirit",
    ["stats.maxHealth"] = "Health",
    ["stats.maxMana"] = "Mana",
    ["stats.maxStamina"] = "Stamina",
    ["stats.attackPower"] = "Attack Power",
    ["stats.spellPower"] = "Spell Power",
    ["stats.armor"] = "Armor",
    ["stats.magicResistance"] = "Magic Resistance",
    ["stats.critChance"] = "Critical Chance",
    ["stats.critMultiplier"] = "Critical Multiplier",
    ["stats.attackSpeed"] = "Attack Speed",

    -----------------------------------------------------------------------
    -- Inventory / items
    -----------------------------------------------------------------------
    ["inventory.title"] = "Inventory",
    ["inventory.empty"] = "Inventory is empty",
    ["inventory.drop"] = "Drop",
    ["inventory.use"] = "Use",
    ["inventory.equip"] = "Equip",
    ["inventory.unequip"] = "Unequip",
    ["inventory.destroy"] = "Destroy",
    ["inventory.split"] = "Split",
    ["inventory.no_space"] = "Not enough space",
    ["inventory.item_received"] = "Received item: %s",
    ["inventory.item_lost"] = "Item lost: %s",
    ["inventory.full"] = "Inventory is full",
    ["inventory.items_count"] = "Items",
    ["inventory.overflow_label"] = "In reserve",
    ["inventory.loading"] = "Loading inventory…",
    ["inventory.sort"] = "Sort",
    ["inventory.invalid_drop_position"] = "That inventory position is invalid",

    ["item.type.weapon"] = "Weapon",
    ["item.type.armor"] = "Armor",
    ["item.type.helmet"] = "Helmet",
    ["item.type.boots"] = "Boots",
    ["item.type.gloves"] = "Gloves",
    ["item.type.ring"] = "Ring",
    ["item.type.amulet"] = "Amulet",
    ["item.type.food"] = "Food",
    ["item.type.drink"] = "Drink",
    ["item.type.consumable"] = "Consumable",
    ["item.type.material"] = "Material",
    ["item.type.quest"] = "Quest Item",
    ["item.type.container"] = "Container",
    ["item.type.currency"] = "Currency",
    ["item.type.misc"] = "Miscellaneous",
    ["item.type.special"] = "Special",

    ["item.weight"] = "Weight",
    ["item.damage"] = "Damage",
    ["item.durability"] = "Durability",
    ["item.requirements"] = "Requirements",
    ["item.required_level"] = "Required Level",
    ["item.required_class"] = "Required Class",
    ["item.required_race"] = "Required Race",
    ["item.broken"] = "Broken",
    ["item.stack"] = "Stack",

    ["rarity.poor"] = "Poor",
    ["rarity.common"] = "Common",
    ["rarity.uncommon"] = "Uncommon",
    ["rarity.rare"] = "Rare",
    ["rarity.epic"] = "Epic",
    ["rarity.legendary"] = "Legendary",
    ["rarity.artifact"] = "Artifact",
    ["rarity.quest"] = "Quest",

    -----------------------------------------------------------------------
    -- Equipment slots
    -----------------------------------------------------------------------
    ["slot.head"] = "Head",
    ["slot.neck"] = "Neck",
    ["slot.shoulders"] = "Shoulders",
    ["slot.chest"] = "Chest",
    ["slot.back"] = "Back",
    ["slot.hands"] = "Hands",
    ["slot.belt"] = "Belt",
    ["slot.legs"] = "Legs",
    ["slot.feet"] = "Feet",
    ["slot.main_hand"] = "Main Hand",
    ["slot.off_hand"] = "Off Hand",
    ["slot.ring_1"] = "Ring 1",
    ["slot.ring_2"] = "Ring 2",
    ["slot.amulet"] = "Amulet",

    -----------------------------------------------------------------------
    -- Equipment / menu
    -----------------------------------------------------------------------
    ["equipment.title"] = "Equipment",
    ["character_menu.title"] = "Character",
    ["character_menu.stats"] = "Stats",
    ["character_menu.inventory"] = "Inventory",
    ["character_menu.equipment"] = "Equipment",
    ["character_menu.quests"] = "Quests",

    -----------------------------------------------------------------------
    -- World / interaction
    -----------------------------------------------------------------------
    ["interact.pickup"] = "Pick up",
    ["interact.talk"] = "Talk",
    ["interact.open"] = "Open",
    ["interact.use"] = "Use",
    ["interact.key"] = "[E]",
    ["resource.coins"] = "Coins",
    ["resource.coins_description"] = "Valuable loot · amount: %d",
    ["hud.level_short"] = "Lv.",
    ["resource.unknown_description"] = "An item that can be picked up.",
    ["interact.npc_vendor"] = "Trade",
    ["interact.npc_quest"] = "Quest",
    ["interact.npc_talk"] = "Talk",
    ["race.human"] = "Human",
    ["race.elf"] = "Night Elf",
    ["race.orc"] = "Orc",
    ["race.dwarf"] = "Dwarf",
    ["race.gnome"] = "Gnome",
    ["race.undead"] = "Undead",
    ["race.tauren"] = "Tauren",
    ["race.troll"] = "Troll",
    ["race.goblin"] = "Goblin",

    -----------------------------------------------------------------------
    -- Progress
    -----------------------------------------------------------------------
    ["xp.gain"] = "+%d XP",
    ["xp.reason.kill"] = "For killing",
    ["xp.reason.quest"] = "For quest",
    ["levelup.text"] = "You have reached level %d!",
    ["levelup.title"] = "Level Up",

    -----------------------------------------------------------------------
    -- Misc
    -----------------------------------------------------------------------
    ["notify.error"] = "Error",
    ["notify.success"] = "Success",
    ["notify.info"] = "Info",
    ["death.title"] = "You died",
    ["death.respawn"] = "Respawning in %d sec.",
    ["currency.name"] = "Coins",
    ["target.none"] = "No target",
    -----------------------------------------------------------------------
    -- Quests / dialogue / vendors
    -----------------------------------------------------------------------
    ["quest.log_title"] = "Quest Log",
    ["quest.log_empty"] = "No quests yet",
    ["quest.status_active"] = "Active",
    ["quest.status_completed"] = "Completed",
    ["quest.track"] = "Track",
    ["quest.untrack"] = "Untrack",
    ["quest.abandon"] = "Abandon",
    ["quest.accepted"] = "Quest accepted",
    ["quest.completed"] = "Quest completed",
    ["quest.abandoned"] = "Quest abandoned",
    ["quest.in_progress"] = "Quest already in progress",
    ["quest.already_completed"] = "Quest already completed",
    ["quest.not_available"] = "Quest unavailable",
    ["quest.no_quests"] = "I have no quests for you",
    ["dialogue.title"] = "Dialogue",
    ["vendor.title"] = "Trade",
    ["vendor.buy"] = "Buy",
    ["vendor.sell"] = "Sell",
    ["vendor.buy_one"] = "Buy",
    ["vendor.sell_one"] = "Sell",
    ["vendor.no_items"] = "Nothing to sell",
    ["vendor.not_enough_money"] = "Not enough coins",
    ["vendor.inventory_full"] = "Inventory is full",
    ["currency.coins"] = "coins",
    ["npc.interact"] = "[E] Interact",
})
