WO.Spells.Register({
    id = "air_burst",
    name = "Порыв воздуха",
    element = "Воздух",
    type = "damage",
    description = "Сгусток голубой энергии поражает цель на расстоянии.",
    requiredLevel = 1,
    maxRank = 5,
    manaCost = 7,
    range = 850,
    cooldown = 1.0,
    basePower = 18,
    powerPerRank = 7,
    spellPowerScale = 0.5,
    damageType = WO.Enums.DamageType.NATURE,
    particle = "pfx1_08~",
    impactParticle = "pfx1_06~",
    impactEffect = "AirboatGunHeavyImpact",
})
