WO.Spells.Register({
    id = "earth_shard",
    name = "Каменный осколок",
    element = "Земля",
    type = "damage",
    description = "Поднимает кислотный сгусток земли и наносит урон.",
    requiredLevel = 1,
    maxRank = 5,
    manaCost = 8,
    range = 800,
    cooldown = 1.2,
    basePower = 21,
    powerPerRank = 8,
    spellPowerScale = 0.5,
    damageType = WO.Enums.DamageType.NATURE,
    particle = "pfx2_03",
    impactParticle = "pfx1_06",
    impactEffect = "cball_bounce",
})
